spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        default-schema: public
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db-changeLog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: password
    username: postgres
security:
  session:
    secretKey: "ivan es un boludo y no me lo banco mas el 21/07/2021 fue el ultimo dia"

