spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        default-schema: public
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db-changeLog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: password
    username: postgres

